# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: post.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'post.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npost.proto\x12\x04post\"J\n\x11PostActionRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0f\n\x07post_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"U\n\x0e\x43ommentRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0f\n\x07post_id\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"A\n\x12GetCommentsRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x0c\n\x04size\x18\x03 \x01(\x05\">\n\x13GetCommentsResponse\x12\'\n\x08\x63omments\x18\x01 \x03(\x0b\x32\x15.post.CommentResponse\"E\n\x0f\x43ommentResponse\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"$\n\x12PostActionResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x8e\x02\n\x0bPostService\x12=\n\x08LikePost\x12\x17.post.PostActionRequest\x1a\x18.post.PostActionResponse\x12=\n\x08ViewPost\x12\x17.post.PostActionRequest\x1a\x18.post.PostActionResponse\x12=\n\x0b\x43ommentPost\x12\x14.post.CommentRequest\x1a\x18.post.PostActionResponse\x12\x42\n\x0bGetComments\x12\x18.post.GetCommentsRequest\x1a\x19.post.GetCommentsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'post_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSTACTIONREQUEST']._serialized_start=20
  _globals['_POSTACTIONREQUEST']._serialized_end=94
  _globals['_COMMENTREQUEST']._serialized_start=96
  _globals['_COMMENTREQUEST']._serialized_end=181
  _globals['_GETCOMMENTSREQUEST']._serialized_start=183
  _globals['_GETCOMMENTSREQUEST']._serialized_end=248
  _globals['_GETCOMMENTSRESPONSE']._serialized_start=250
  _globals['_GETCOMMENTSRESPONSE']._serialized_end=312
  _globals['_COMMENTRESPONSE']._serialized_start=314
  _globals['_COMMENTRESPONSE']._serialized_end=383
  _globals['_POSTACTIONRESPONSE']._serialized_start=385
  _globals['_POSTACTIONRESPONSE']._serialized_end=421
  _globals['_POSTSERVICE']._serialized_start=424
  _globals['_POSTSERVICE']._serialized_end=694
# @@protoc_insertion_point(module_scope)
