# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analytics.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'analytics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61nalytics.proto\x12\tanalytics\" \n\rPostIdRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\t\"o\n\nTopRequest\x12\x31\n\tstat_type\x18\x01 \x01(\x0e\x32\x1e.analytics.TopRequest.StatType\".\n\x08StatType\x12\t\n\x05VIEWS\x10\x00\x12\t\n\x05LIKES\x10\x01\x12\x0c\n\x08\x43OMMENTS\x10\x02\"T\n\x11PostStatsResponse\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\r\n\x05views\x18\x02 \x01(\x03\x12\r\n\x05likes\x18\x03 \x01(\x03\x12\x10\n\x08\x63omments\x18\x04 \x01(\x03\"+\n\x0c\x44ynamicsItem\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\":\n\x10\x44ynamicsResponse\x12&\n\x05items\x18\x01 \x03(\x0b\x32\x17.analytics.DynamicsItem\"s\n\x10TopPostsResponse\x12\x33\n\x05posts\x18\x01 \x03(\x0b\x32$.analytics.TopPostsResponse.PostInfo\x1a*\n\x08PostInfo\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\"s\n\x10TopUsersResponse\x12\x33\n\x05users\x18\x01 \x03(\x0b\x32$.analytics.TopUsersResponse.UserInfo\x1a*\n\x08UserInfo\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\x32\xd0\x03\n\x10\x41nalyticsService\x12\x46\n\x0cGetPostStats\x12\x18.analytics.PostIdRequest\x1a\x1c.analytics.PostStatsResponse\x12M\n\x14GetPostViewsDynamics\x12\x18.analytics.PostIdRequest\x1a\x1b.analytics.DynamicsResponse\x12M\n\x14GetPostLikesDynamics\x12\x18.analytics.PostIdRequest\x1a\x1b.analytics.DynamicsResponse\x12P\n\x17GetPostCommentsDynamics\x12\x18.analytics.PostIdRequest\x1a\x1b.analytics.DynamicsResponse\x12\x41\n\x0bGetTopPosts\x12\x15.analytics.TopRequest\x1a\x1b.analytics.TopPostsResponse\x12\x41\n\x0bGetTopUsers\x12\x15.analytics.TopRequest\x1a\x1b.analytics.TopUsersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analytics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSTIDREQUEST']._serialized_start=30
  _globals['_POSTIDREQUEST']._serialized_end=62
  _globals['_TOPREQUEST']._serialized_start=64
  _globals['_TOPREQUEST']._serialized_end=175
  _globals['_TOPREQUEST_STATTYPE']._serialized_start=129
  _globals['_TOPREQUEST_STATTYPE']._serialized_end=175
  _globals['_POSTSTATSRESPONSE']._serialized_start=177
  _globals['_POSTSTATSRESPONSE']._serialized_end=261
  _globals['_DYNAMICSITEM']._serialized_start=263
  _globals['_DYNAMICSITEM']._serialized_end=306
  _globals['_DYNAMICSRESPONSE']._serialized_start=308
  _globals['_DYNAMICSRESPONSE']._serialized_end=366
  _globals['_TOPPOSTSRESPONSE']._serialized_start=368
  _globals['_TOPPOSTSRESPONSE']._serialized_end=483
  _globals['_TOPPOSTSRESPONSE_POSTINFO']._serialized_start=441
  _globals['_TOPPOSTSRESPONSE_POSTINFO']._serialized_end=483
  _globals['_TOPUSERSRESPONSE']._serialized_start=485
  _globals['_TOPUSERSRESPONSE']._serialized_end=600
  _globals['_TOPUSERSRESPONSE_USERINFO']._serialized_start=558
  _globals['_TOPUSERSRESPONSE_USERINFO']._serialized_end=600
  _globals['_ANALYTICSSERVICE']._serialized_start=603
  _globals['_ANALYTICSSERVICE']._serialized_end=1067
# @@protoc_insertion_point(module_scope)
